name: Awesome ChatGPT Prompts
title: null

# Dark mode configuration
dark_mode: true

# GitHub Pages configuration
github_pages:
  url: "https://ahmed.github.io/awesome-chatgpt-prompts"
  branch: "gh-pages"
